# Generated by Django 5.2.1 on 2025-09-16 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favorite', '0001_initial'),
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites_received', to='word.words'),
        ),
    ]
