# Generated by Django 5.2.1 on 2025-07-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words',
            old_name='category_id',
            new_name='category',
        ),
    ]
