# Generated by Django 5.0.7 on 2024-07-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alphabets_item',
            old_name='title',
            new_name='alphabet_item_title',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='category_title',
        ),
    ]
