# Generated by Django 5.2.1 on 2025-08-03 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0002_alter_favorite_created_by_alter_favorite_word'),
        ('word', '0003_alter_category_created_by_alter_words_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='favorite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='favorite.favorite'),
        ),
    ]
